name: Déployer l'application Vue.js sur Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm install

      - name: Construire l'application
        run: npm run build

      - name: Déployer sur Hostinger via FTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: 'dist/*'
          target: '/public_html/'
